"""empty message

Revision ID: 329aed4691f4
Revises: 14f9d63394b9
Create Date: 2023-03-17 14:14:38.395948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329aed4691f4'
down_revision = '14f9d63394b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_no', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reg_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_no', sa.VARCHAR(length=10), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('reg_no')

    # ### end Alembic commands ###
