"""empty message

Revision ID: 6aeb1e312871
Revises: 6550cfe35a13
Create Date: 2023-03-17 13:26:08.368508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6aeb1e312871'
down_revision = '6550cfe35a13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('reg_no')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_no', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reg_no')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_no', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
